### ISSUE TITLE
INTEGER type parsing incorrectly

### ISSUE THREAD

**Issue by ashersaupingomez** [denodrivers/sqlite3#11]
Hi there, INTEGER type data doesn't seem to be getting parsed correctly. Here's how to recreate:
Table schema and data:
```
CREATE TABLE dates (dates INTEGER);
INSERT INTO dates (dates) VALUES (978307200000);
INSERT INTO dates (dates) VALUES (1009843200000);
INSERT INTO dates (dates) VALUES (1041379200000);
INSERT INTO dates (dates) VALUES (1072915200000);
INSERT INTO dates (dates) VALUES (1104537600000);
```

Via the CLI:
```
SELECT * FROM dates;
```
Returns, as expected:
```
978307200000
1009843200000
1041379200000
1072915200000
1104537600000
```

The following code:
```js
import { Database } from "https://deno.land/x/sqlite3@0.2.4/mod.ts";

const db = new Database("test.db");

const results = db.queryArray(`
  SELECT *
  FROM dates
`);

console.log(results);

db.close();
```
Returns, incorrectly:
```js
[ [ -945343488 ], [ 525885440 ], [ 1997114368 ], [ -826624000 ], [ 731004928 ] ]
```

Deno version: 1.17.1 (release, x86_64-apple-darwin)
Module version: 0.2.3
macOS version: 12.1
SQLite version: 3.37.0

**Comment by DjDeveloperr** [comment]
I think that's because it's parsing all integer type columns as 32-bit integers. I will fix this asap

**Comment by DjDeveloperr** [comment]
Fix released in 0.2.5

**Comment by ashersaupingomez** [comment]
Legend! Thank you 🙏🏾

**Comment by Hexagon** [comment]
@DjDeveloperr 

This problem seem to be back in `0.8.3`

CLI:
SELECT MAX(period) FROM spotprice
1678572000000

Deno sqlite3 0.8.3
prepare('SELECT MAX(period) FROM spotprice').values()
[ [ -760212736 ] ]

**Comment by DjDeveloperr** [comment]
@Hexagon See doc.md. It's a performance optimization to always prefer 32-bit integers over 64-bit. SQLite API does not differentiate between both in value type, hence the preference. 

If you want to serialize as 64 bit either set int64: true in DB options or temporarily set it in DB's property to avoid performance deopt. 

Performance issue is because the FFI API cannot use BigInts in fast path, but this may change in future, so both options will become performant.

**Comment by Hexagon** [comment]
@DjDeveloperr Sorry about that! I searched the docs and googled and somehow missed that the option were listed at top of documentation 😅 

However, this got me thinking. Is there really any performance gain from having this error prone option defaulted to int32?

Afaik both sqlite and javascript handle 64bit integers (and nothing above that) ootb. Wouldn't it be possible to change https://github.com/denodrivers/sqlite3/blob/33946c29151a31584ba86644fe7e06f7285fd409/src/statement.ts#L74

to

```ts
if (ty === SQLITE_INTEGER) return sqlite3_column_int64(handle, i);
```

and drop this clause (containing a possibly slow bignum check) altogether

https://github.com/denodrivers/sqlite3/blob/33946c29151a31584ba86644fe7e06f7285fd409/src/statement.ts#L83

**Comment by DjDeveloperr** [comment]
#sqlite3_column_int is faster than sqlite3_column_int64 because the latter makes a heap allocation to store the result value as 64 bit integers are not directly supported by V8 Fast API yet. It's just an implementation detail behind the FFI API, which is likely going to change in future as returning 64 bit numbers as BigInts may become possible via Fast API, at least that's the plan.

**Comment by Hexagon** [comment]
I see, thanks for taking time to answer 👍
