### ISSUE TITLE
Support promise

### ISSUE THREAD

**Issue by fushihara** [denodrivers/sqlite3#136]
All the operation APIs are synchronous processes, but I would like to see a modern Promise-based API provided.

**Comment by DjDeveloperr** [comment]
It is intentional here to offer sync APIs only for performance reasons. SQLite unlike other databases, is in-process and does not involve over the network I/O - which we usually do asynchronously. Here, we only have file I/O, and it's really quick most of the times that making it async manually by offloading the work to another thread only introduces more overhead. SQLite3 C API does not offer any asynchronous API. You can always make a new Web Worker, make an SQLite DB instance in that and operate over messages to make it asynchronous and not block the main thread.

Being asynchronous or not is not a matter of being modern. Sometimes, it's just mostly unnecessary to make something asynchronous. The fastest SQLite3 driver for Node.js is `better-sqlite3`, it is also sync, and so is `bun:sqlite`. All three including this project offer very similar sync API. Is the synchronous API causing any problems in your application?

**Comment by fushihara** [comment]
I did not know that you intentionally provide a synchronous API.
I understood that it is a very low priority.
I will close the issue for now.
Still, I have an idea that I would like to have an asynchronous API, so I will promote the advantages.

Even though file I/O is very fast, throwing heavy queries is a real problem. It is not always correct to make the query a light process, and there are cases where heavy processing is the right answer.
If the program is dedicated only to sqlite operations, there is no problem, but since programs usually do a lot of processing, there is a real possibility that they will be dragged down by the synchronous sqlite.

I don't think that being fast in most cases is a reason why the asynchronous API is unnecessary.
Do you only use the synchronous API because the file write API is “mostly” fast?
I always use the asynchronous API for any light file write.

Thanks!

**Comment by digitalnature** [comment]
I think both aync and async API have their advantages. In a real-world app, if you have many requests that overlap, async API would make the server be able to handle all of them at the same time, especially if you are using transactions, while the sync version would need to wait for queries to complete before handling another request. 

A wrapper can be written using web workers to split the processing into multiple threads, however this increases complexity of the app quite a lot and adds more typescript issues that need to be handled.
Transactions are a must, and being able to make them async using web workers is not that straight-forward. A lot messages need to be exchanged between parent and child process, paramters serialized, typescript  pleased...
Native multi-threading would be ideal.
