### ISSUE TITLE
[uncaught application error]: TypeError - db.queryObject is not a function

### ISSUE THREAD

**Issue by ralyodio** [denodrivers/sqlite3#48]
Getting this on 0.5.0 now

**Comment by ralyodio** [comment]
I'm guessing queryArray is missing now too.

**Comment by DjDeveloperr** [comment]
Yep - I'll add a separate documentation file to explain every method in better way for beginners of the library. For now you can check doc.deno.land link as mentioned in readme and look for `Database` and `Statement` objects. Methods docs there should have examples with them. Since it is present in JSDoc, may as well look for it in your code editor.

- `execute` is now `exec`
- `queryObject` -> `prepare(sql).all(...params)`
- `queryArray` -> `prepare(sql).values(...params)`

It is recommended to cache Statement from `prepare` method if its used again and again. That way it is compiled only once and is faster to run consequently.

**Comment by DjDeveloperr** [comment]
Now that there's better documentation, hope it resolves any issues!

**Comment by DjDeveloperr** [comment]
Same as queries but instead of all/values method, just use `stmt.run(...params)`
